# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Enquires'},
        ),
    ]
