# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_sport_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
