# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_sport_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sport',
            name='image4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sport',
            name='image5',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sport',
            name='image6',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
