# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sport', '0001_initial'),
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('designation', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('google_plus_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('centers', models.ManyToManyField(to='center.Center')),
                ('sports', models.ManyToManyField(to='sport.Sport')),
            ],
        ),
    ]
