# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
