# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='evening_closing_timing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='evening_opening_timing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='center',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='center',
            name='morning_closing_timing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='morning_opening_timing',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
