# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20190209_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
